// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ohagey.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Ohagey IPC schema (decision 0007).
//
// Protocol between the C++ TSF client (tsf/) and the Swift conversion server
// (engine/), spoken over a session-scoped named pipe (decision 0006).
//
// FRAMING: a named pipe is a byte stream and Protobuf is not self-delimiting,
// so every message is length-prefixed: a 4-byte little-endian uint32 giving
// the serialized payload length, followed by that many bytes of a serialized
// `Request` (client -> server) or `Response` (server -> client).
//
// STATUS: this is the initial v1 draft. Field details may be refined during
// implementation (see docs/decisions/README.md "実装フェーズで詰める残課題").

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Ohagey_Ipc_V1_Backend: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// decision 0010
  case cpu // = 1
  case cuda // = 2
  case vulkan // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .cpu
    case 2: self = .cuda
    case 3: self = .vulkan
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .cpu: return 1
    case .cuda: return 2
    case .vulkan: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ohagey_Ipc_V1_Backend] = [
    .unspecified,
    .cpu,
    .cuda,
    .vulkan,
  ]

}

/// A single client request. `request_id` correlates with `Response.request_id`
/// so the client can pipeline requests on one connection.
public nonisolated struct Ohagey_Ipc_V1_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: UInt32 = 0

  public var kind: Ohagey_Ipc_V1_Request.OneOf_Kind? = nil

  public var convert: Ohagey_Ipc_V1_ConvertRequest {
    get {
      if case .convert(let v)? = kind {return v}
      return Ohagey_Ipc_V1_ConvertRequest()
    }
    set {kind = .convert(newValue)}
  }

  public var commit: Ohagey_Ipc_V1_CommitRequest {
    get {
      if case .commit(let v)? = kind {return v}
      return Ohagey_Ipc_V1_CommitRequest()
    }
    set {kind = .commit(newValue)}
  }

  public var registerWord: Ohagey_Ipc_V1_RegisterWordRequest {
    get {
      if case .registerWord(let v)? = kind {return v}
      return Ohagey_Ipc_V1_RegisterWordRequest()
    }
    set {kind = .registerWord(newValue)}
  }

  public var ping: Ohagey_Ipc_V1_PingRequest {
    get {
      if case .ping(let v)? = kind {return v}
      return Ohagey_Ipc_V1_PingRequest()
    }
    set {kind = .ping(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Kind: Equatable, Sendable {
    case convert(Ohagey_Ipc_V1_ConvertRequest)
    case commit(Ohagey_Ipc_V1_CommitRequest)
    case registerWord(Ohagey_Ipc_V1_RegisterWordRequest)
    case ping(Ohagey_Ipc_V1_PingRequest)

  }

  public init() {}
}

/// The server reply for the `Request` with the matching `request_id`.
public nonisolated struct Ohagey_Ipc_V1_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: UInt32 = 0

  public var status: Ohagey_Ipc_V1_Status {
    get {_status ?? Ohagey_Ipc_V1_Status()}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {self._status = nil}

  public var kind: Ohagey_Ipc_V1_Response.OneOf_Kind? = nil

  public var convert: Ohagey_Ipc_V1_ConvertResponse {
    get {
      if case .convert(let v)? = kind {return v}
      return Ohagey_Ipc_V1_ConvertResponse()
    }
    set {kind = .convert(newValue)}
  }

  public var commit: Ohagey_Ipc_V1_CommitResponse {
    get {
      if case .commit(let v)? = kind {return v}
      return Ohagey_Ipc_V1_CommitResponse()
    }
    set {kind = .commit(newValue)}
  }

  public var registerWord: Ohagey_Ipc_V1_RegisterWordResponse {
    get {
      if case .registerWord(let v)? = kind {return v}
      return Ohagey_Ipc_V1_RegisterWordResponse()
    }
    set {kind = .registerWord(newValue)}
  }

  public var ping: Ohagey_Ipc_V1_PingResponse {
    get {
      if case .ping(let v)? = kind {return v}
      return Ohagey_Ipc_V1_PingResponse()
    }
    set {kind = .ping(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Kind: Equatable, Sendable {
    case convert(Ohagey_Ipc_V1_ConvertResponse)
    case commit(Ohagey_Ipc_V1_CommitResponse)
    case registerWord(Ohagey_Ipc_V1_RegisterWordResponse)
    case ping(Ohagey_Ipc_V1_PingResponse)

  }

  public init() {}

  fileprivate var _status: Ohagey_Ipc_V1_Status? = nil
}

public nonisolated struct Ohagey_Ipc_V1_Status: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: Ohagey_Ipc_V1_Status.Code = .ok

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Code: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case ok // = 0
    case invalidArgument // = 1
    case `internal` // = 2
    case modelUnavailable // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .ok
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .ok
      case 1: self = .invalidArgument
      case 2: self = .internal
      case 3: self = .modelUnavailable
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .ok: return 0
      case .invalidArgument: return 1
      case .internal: return 2
      case .modelUnavailable: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Ohagey_Ipc_V1_Status.Code] = [
      .ok,
      .invalidArgument,
      .internal,
      .modelUnavailable,
    ]

  }

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_ConvertRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Composition string to convert, as hiragana yomi.
  public var reading: String = String()

  /// Max candidates requested; 0 means "engine default".
  public var nBest: UInt32 = 0

  public var context: Ohagey_Ipc_V1_ConversionContext {
    get {_context ?? Ohagey_Ipc_V1_ConversionContext()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {self._context = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _context: Ohagey_Ipc_V1_ConversionContext? = nil
}

public nonisolated struct Ohagey_Ipc_V1_ConversionContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Already-committed left context, to inform Zenzai's neural prediction.
  public var precedingText: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_ConvertResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var candidates: [Ohagey_Ipc_V1_Candidate] = []

  /// false => dictionary-only fallback because the Zenzai model is unavailable
  /// (decision 0008). The UI may surface this state.
  public var zenzaiUsed: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_Candidate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Surface form shown to the user.
  public var text: String = String()

  /// Yomi for the surface form (used for partial commit / relearning).
  public var reading: String = String()

  /// Engine rank hint; higher is better. Optional (0 if unset).
  public var score: Int32 = 0

  /// Bunsetsu-level sub-segments, when the engine provides them, so the client
  /// can support per-segment reconversion.
  public var segments: [Ohagey_Ipc_V1_Segment] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_Segment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var text: String = String()

  public var reading: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_CommitRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reading: String = String()

  public var text: String = String()

  /// Honor the per-user learning toggle at the caller: when false the commit
  /// must not update the learning store (decision 0025).
  public var updateLearning: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_CommitResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_RegisterWordRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// yomi
  public var reading: String = String()

  /// registered word
  public var surface: String = String()

  /// optional POS hint
  public var partOfSpeech: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_RegisterWordResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_PingRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ohagey_Ipc_V1_PingResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var engineVersion: String = String()

  public var modelLoaded: Bool = false

  public var backend: Ohagey_Ipc_V1_Backend = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ohagey.ipc.v1"

nonisolated extension Ohagey_Ipc_V1_Backend: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BACKEND_UNSPECIFIED\0\u{1}BACKEND_CPU\0\u{1}BACKEND_CUDA\0\u{1}BACKEND_VULKAN\0")
}

nonisolated extension Ohagey_Ipc_V1_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}convert\0\u{1}commit\0\u{3}register_word\0\u{1}ping\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.requestID) }()
      case 2: try {
        var v: Ohagey_Ipc_V1_ConvertRequest?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .convert(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .convert(v)
        }
      }()
      case 3: try {
        var v: Ohagey_Ipc_V1_CommitRequest?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .commit(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .commit(v)
        }
      }()
      case 4: try {
        var v: Ohagey_Ipc_V1_RegisterWordRequest?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .registerWord(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .registerWord(v)
        }
      }()
      case 5: try {
        var v: Ohagey_Ipc_V1_PingRequest?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .ping(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .ping(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt32Field(value: self.requestID, fieldNumber: 1)
    }
    switch self.kind {
    case .convert?: try {
      guard case .convert(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .commit?: try {
      guard case .commit(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .registerWord?: try {
      guard case .registerWord(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .ping?: try {
      guard case .ping(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_Request, rhs: Ohagey_Ipc_V1_Request) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}status\0\u{1}convert\0\u{1}commit\0\u{3}register_word\0\u{1}ping\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._status) }()
      case 3: try {
        var v: Ohagey_Ipc_V1_ConvertResponse?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .convert(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .convert(v)
        }
      }()
      case 4: try {
        var v: Ohagey_Ipc_V1_CommitResponse?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .commit(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .commit(v)
        }
      }()
      case 5: try {
        var v: Ohagey_Ipc_V1_RegisterWordResponse?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .registerWord(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .registerWord(v)
        }
      }()
      case 6: try {
        var v: Ohagey_Ipc_V1_PingResponse?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .ping(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .ping(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt32Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._status {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    switch self.kind {
    case .convert?: try {
      guard case .convert(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .commit?: try {
      guard case .commit(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .registerWord?: try {
      guard case .registerWord(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .ping?: try {
      guard case .ping(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_Response, rhs: Ohagey_Ipc_V1_Response) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._status != rhs._status {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_Status: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Status"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .ok {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_Status, rhs: Ohagey_Ipc_V1_Status) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_Status.Code: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CODE_OK\0\u{1}CODE_INVALID_ARGUMENT\0\u{1}CODE_INTERNAL\0\u{1}CODE_MODEL_UNAVAILABLE\0")
}

nonisolated extension Ohagey_Ipc_V1_ConvertRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConvertRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reading\0\u{3}n_best\0\u{1}context\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.nBest) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 1)
    }
    if self.nBest != 0 {
      try visitor.visitSingularUInt32Field(value: self.nBest, fieldNumber: 2)
    }
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_ConvertRequest, rhs: Ohagey_Ipc_V1_ConvertRequest) -> Bool {
    if lhs.reading != rhs.reading {return false}
    if lhs.nBest != rhs.nBest {return false}
    if lhs._context != rhs._context {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_ConversionContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConversionContext"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}preceding_text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.precedingText) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.precedingText.isEmpty {
      try visitor.visitSingularStringField(value: self.precedingText, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_ConversionContext, rhs: Ohagey_Ipc_V1_ConversionContext) -> Bool {
    if lhs.precedingText != rhs.precedingText {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_ConvertResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConvertResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}candidates\0\u{3}zenzai_used\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.candidates) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.zenzaiUsed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.candidates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.candidates, fieldNumber: 1)
    }
    if self.zenzaiUsed != false {
      try visitor.visitSingularBoolField(value: self.zenzaiUsed, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_ConvertResponse, rhs: Ohagey_Ipc_V1_ConvertResponse) -> Bool {
    if lhs.candidates != rhs.candidates {return false}
    if lhs.zenzaiUsed != rhs.zenzaiUsed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_Candidate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Candidate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}reading\0\u{1}score\0\u{1}segments\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.score) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.segments) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 2)
    }
    if self.score != 0 {
      try visitor.visitSingularInt32Field(value: self.score, fieldNumber: 3)
    }
    if !self.segments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.segments, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_Candidate, rhs: Ohagey_Ipc_V1_Candidate) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.reading != rhs.reading {return false}
    if lhs.score != rhs.score {return false}
    if lhs.segments != rhs.segments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_Segment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Segment"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}reading\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_Segment, rhs: Ohagey_Ipc_V1_Segment) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.reading != rhs.reading {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_CommitRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommitRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reading\0\u{1}text\0\u{3}update_learning\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.updateLearning) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 1)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 2)
    }
    if self.updateLearning != false {
      try visitor.visitSingularBoolField(value: self.updateLearning, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_CommitRequest, rhs: Ohagey_Ipc_V1_CommitRequest) -> Bool {
    if lhs.reading != rhs.reading {return false}
    if lhs.text != rhs.text {return false}
    if lhs.updateLearning != rhs.updateLearning {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_CommitResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommitResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_CommitResponse, rhs: Ohagey_Ipc_V1_CommitResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_RegisterWordRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RegisterWordRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reading\0\u{1}surface\0\u{3}part_of_speech\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.surface) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.partOfSpeech) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 1)
    }
    if !self.surface.isEmpty {
      try visitor.visitSingularStringField(value: self.surface, fieldNumber: 2)
    }
    if !self.partOfSpeech.isEmpty {
      try visitor.visitSingularStringField(value: self.partOfSpeech, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_RegisterWordRequest, rhs: Ohagey_Ipc_V1_RegisterWordRequest) -> Bool {
    if lhs.reading != rhs.reading {return false}
    if lhs.surface != rhs.surface {return false}
    if lhs.partOfSpeech != rhs.partOfSpeech {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_RegisterWordResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RegisterWordResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_RegisterWordResponse, rhs: Ohagey_Ipc_V1_RegisterWordResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_PingRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PingRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_PingRequest, rhs: Ohagey_Ipc_V1_PingRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ohagey_Ipc_V1_PingResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PingResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}engine_version\0\u{3}model_loaded\0\u{1}backend\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.engineVersion) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.modelLoaded) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.backend) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.engineVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.engineVersion, fieldNumber: 1)
    }
    if self.modelLoaded != false {
      try visitor.visitSingularBoolField(value: self.modelLoaded, fieldNumber: 2)
    }
    if self.backend != .unspecified {
      try visitor.visitSingularEnumField(value: self.backend, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ohagey_Ipc_V1_PingResponse, rhs: Ohagey_Ipc_V1_PingResponse) -> Bool {
    if lhs.engineVersion != rhs.engineVersion {return false}
    if lhs.modelLoaded != rhs.modelLoaded {return false}
    if lhs.backend != rhs.backend {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
