# Builds and runs the wire-format selftest (decisions 0007 / 0032). Needs
# nothing running.
#
# Updating Ohagey always produces a mixed pair: the engine is replaced when the
# installer runs, while the TSF DLL waits for a restart because it is loaded
# into every application with a text field. Between those two events every
# conversion on the machine is a new engine talking to an old client.
#
# The engine side is generated by swift-protobuf; this side is hand-written,
# and SkipField is the one function standing between "a field was added to the
# reply" and "the IME stops producing candidates".
param([switch]$KeepIntermediates)

$ErrorActionPreference = "Stop"
$here = $PSScriptRoot
$out = Join-Path $here "build"

if (-not $env:VCINSTALLDIR) {
    $vcvars = "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat"
    if (-not (Test-Path $vcvars)) {
        $vcvars = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
    }
    if (-not (Test-Path $vcvars)) { throw "vcvars64.bat not found; run from an x64 Native Tools prompt" }
    foreach ($line in (cmd.exe /c "`"$vcvars`" && set")) {
        if ($line -match '^([^=]+)=(.*)$') {
            [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2], 'Process')
        }
    }
}

New-Item -ItemType Directory -Force $out | Out-Null

& cl.exe /nologo /std:c++17 /EHsc /utf-8 /W4 /WX /Zi `
    /Fo"$out\" /Fd"$out\wire.pdb" /Fe"$out\wire-selftest.exe" `
    (Join-Path $here "wire-selftest.cpp") (Join-Path $here "..\OhageyWire.cpp") `
    /link kernel32.lib
if ($LASTEXITCODE -ne 0) { throw "build failed" }

Write-Host ""
& "$out\wire-selftest.exe"
$exit = $LASTEXITCODE

if (-not $KeepIntermediates) {
    Get-ChildItem $out -Filter *.obj -ErrorAction SilentlyContinue | Remove-Item -Force
}
exit $exit
