// Does the hand-written reader survive a newer engine's reply? (decision 0007 / 0032)
//
// ── Why this exists ─────────────────────────────────────────────────────────
//
// Updating Ohagey always produces a mixed pair. The engine is replaced the
// moment the installer runs; the TSF DLL cannot be, because it is loaded into
// every application with a text field, so it waits for a restart (decision 0033
// addendum 6). **Between those two events every conversion on the machine is a
// new engine talking to an old client.** That is not a corner case to plan for
// later — it happens on every single update, to everyone.
//
// The engine's side of the wire is generated by swift-protobuf and handles
// unknown fields as a matter of course. This side is hand-written (decision
// 0032), and `SkipField` is the single function standing between "a field was
// added to the reply" and "the IME stops producing candidates". Nothing tested
// it until this file.
//
// Runs entirely in-process against buffers built here: no engine, no pipe, no
// profile. Add cases when ohagey.proto grows a shape this does not cover.

#include "../OhageyWire.h"

#include <cstdio>
#include <string>
#include <vector>

using namespace Ohagey;

namespace
{
    int failures = 0;

    void Check(bool condition, const char* what)
    {
        printf("%-62s %s\n", what, condition ? "ok" : "FAILED");
        if (!condition) ++failures;
    }

    // A reply as some future engine might send it: the fields this build knows,
    // with one it does not, in between.
    std::vector<uint8_t> ReplyWithUnknown(uint32_t unknownField, Wire::WireType type)
    {
        std::vector<uint8_t> body;
        Wire::WriteString(body, 1, L"変換");   // a known field first

        Wire::WriteTag(body, unknownField, type);
        switch (type)
        {
        case Wire::Varint:
            Wire::WriteVarint(body, 300);
            break;
        case Wire::LengthDelimited:
        {
            const std::vector<uint8_t> blob(5, 0x7F);
            Wire::WriteVarint(body, blob.size());
            body.insert(body.end(), blob.begin(), blob.end());
            break;
        }
        case Wire::Fixed32:
            for (int i = 0; i < 4; ++i) body.push_back(0xAB);
            break;
        case Wire::Fixed64:
            for (int i = 0; i < 8; ++i) body.push_back(0xCD);
            break;
        default:
            break;
        }

        Wire::WriteUInt32(body, 2, 42);                // and a known field after
        return body;
    }

    // Reads field 1 (string) and field 2 (uint32), skipping everything else —
    // which is exactly the shape of every parser in OhageyEngineClient.cpp.
    bool ReadKnownFields(const std::vector<uint8_t>& body, std::wstring* text, uint32_t* number)
    {
        Wire::Reader reader(body.data(), body.size());
        while (!reader.AtEnd())
        {
            uint32_t field = 0;
            Wire::WireType type = Wire::Varint;
            if (!reader.ReadTag(&field, &type)) return false;

            if (field == 1 && type == Wire::LengthDelimited)
            {
                if (!reader.ReadString(text)) return false;
            }
            else if (field == 2 && type == Wire::Varint)
            {
                if (!reader.ReadUInt32(number)) return false;
            }
            else if (!reader.SkipField(type))
            {
                return false;
            }
        }
        return reader.Ok();
    }

    void UnknownFieldOfEveryType()
    {
        const struct { Wire::WireType type; const char* name; } kinds[] = {
            { Wire::Varint,          "varint" },
            { Wire::LengthDelimited, "length-delimited" },
            { Wire::Fixed32,         "fixed32" },
            { Wire::Fixed64,         "fixed64" },
        };

        for (const auto& kind : kinds)
        {
            std::wstring text;
            uint32_t number = 0;
            const bool ok = ReadKnownFields(ReplyWithUnknown(9, kind.type), &text, &number);

            char what[128] = {'\0'};
            // The field *after* the unknown one is the point: skipping the wrong
            // number of bytes does not fail, it silently misreads what follows.
            _snprintf_s(what, _TRUNCATE, "unknown %s field is skipped, later fields intact", kind.name);
            Check(ok && text == L"変換" && number == 42, what);
        }
    }

    void UnknownFieldWithAHighNumber()
    {
        // Field numbers past 15 take two bytes of tag. A reader that assumed
        // one would resynchronise onto the middle of a field.
        std::wstring text;
        uint32_t number = 0;
        const bool ok = ReadKnownFields(ReplyWithUnknown(2000, Wire::Varint), &text, &number);
        Check(ok && text == L"変換" && number == 42,
              "unknown field with a multi-byte tag is skipped");
    }

    void TruncatedInputFails()
    {
        // A reply cut short must be reported, not half-believed. This is the
        // other half of forward compatibility: skipping is only safe if running
        // off the end is detected.
        std::vector<uint8_t> body = ReplyWithUnknown(9, Wire::LengthDelimited);
        body.resize(body.size() - 3);

        std::wstring text;
        uint32_t number = 0;
        Check(!ReadKnownFields(body, &text, &number), "a truncated message is rejected");
    }

    void LengthBeyondTheBufferFails()
    {
        // A length prefix larger than what is left. Believing it is a read past
        // the end of the buffer, inside the user's application.
        std::vector<uint8_t> body;
        Wire::WriteTag(body, 9, Wire::LengthDelimited);
        Wire::WriteVarint(body, 4096);
        body.push_back(0x01);

        std::wstring text;
        uint32_t number = 0;
        Check(!ReadKnownFields(body, &text, &number), "a length past the end is rejected");
    }

    void EmptyMessageIsFine()
    {
        // `PingRequest{}` and the oneof cases with no fields are empty on the
        // wire, and reading nothing must not look like a failure.
        std::wstring text;
        uint32_t number = 0;
        Check(ReadKnownFields({}, &text, &number) && text.empty() && number == 0,
              "an empty message reads as empty, not as an error");
    }

    void KnownFieldWithTheWrongTypeIsSkipped()
    {
        // A field this build knows, sent with a different wire type — what a
        // schema change from string to message would look like from here.
        std::vector<uint8_t> body;
        Wire::WriteTag(body, 1, Wire::Varint);
        Wire::WriteVarint(body, 7);
        Wire::WriteUInt32(body, 2, 42);

        std::wstring text;
        uint32_t number = 0;
        Check(ReadKnownFields(body, &text, &number) && text.empty() && number == 42,
              "a known field with an unexpected type does not derail the rest");
    }
}

int main()
{
    UnknownFieldOfEveryType();
    UnknownFieldWithAHighNumber();
    TruncatedInputFails();
    LengthBeyondTheBufferFails();
    EmptyMessageIsFine();
    KnownFieldWithTheWrongTypeIsSkipped();

    printf("\n%s\n", failures == 0 ? "ALL PASSED" : "FAILURES ABOVE");
    return failures == 0 ? 0 : 1;
}
